package com.myg.controlplane.safety;

public enum GuardrailViolationCode {
    KILL_SWITCH_ACTIVE,
    ENVIRONMENT_NOT_ALLOWED,
    MAX_DURATION_EXCEEDED,
    LATENCY_AMOUNT_REQUIRED,
    LATENCY_AMOUNT_EXCEEDED,
    TRAFFIC_PERCENTAGE_REQUIRED,
    TRAFFIC_PERCENTAGE_INVALID,
    APPROVAL_REQUIRED,
    APPROVAL_INVALID
}
