package com.myg.controlplane.safety;

public enum GuardrailViolationCode {
    KILL_SWITCH_ACTIVE,
    ENVIRONMENT_NOT_ALLOWED,
    MAX_DURATION_EXCEEDED,
    APPROVAL_REQUIRED,
    APPROVAL_INVALID,
    HTTP_ERROR_CODE_REQUIRED,
    HTTP_ERROR_CODE_UNSUPPORTED,
    TRAFFIC_PERCENTAGE_REQUIRED
}
