package com.myg.controlplane.safety;

public enum GuardrailViolationCode {
    KILL_SWITCH_ACTIVE,
    ENVIRONMENT_NOT_ALLOWED,
    MAX_DURATION_EXCEEDED,
    UNSUPPORTED_FAULT_TYPE,
    LATENCY_AMOUNT_REQUIRED,
    LATENCY_AMOUNT_EXCEEDED,
    LATENCY_JITTER_INVALID,
    LATENCY_JITTER_EXCEEDED,
    LATENCY_BOUNDS_REQUIRED,
    LATENCY_BOUNDS_INVALID,
    LATENCY_CONFIGURATION_CONFLICT,
    TRAFFIC_PERCENTAGE_REQUIRED,
    TRAFFIC_PERCENTAGE_INVALID,
    DROP_PERCENTAGE_REQUIRED,
    DROP_PERCENTAGE_INVALID,
    APPROVAL_REQUIRED,
    APPROVAL_INVALID,
    HTTP_ERROR_CODE_REQUIRED,
    HTTP_ERROR_CODE_UNSUPPORTED
}
